# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui.autosave'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

'''
BUGS:
1) Sometimes when buying a product (which in effect just deletes it), another product will also randomly be deleted.
2) Possibility fewer than eight products being displayed on homepage when there are at least 8 products to display. 
3) There is a very very very small chance that two products could be given the same ID, which is how I distinguish between
products. The random ID's are 10 characters long of a combination of letters and numbers. The application does not check
if an ID already exists, so in theory, two products could potentially have the same ID. 
4) On the search results page, if more than two products are displayed, all displayed results become scrunched together. This is
because the QScrollArea Widget I used would not allow for srolling for some reason. My T.A. looked at it with me, and he could
not figure it out why the scroll bar was not appearing either. The QScrollArea widget is created on line 277 of this file. 

LIMITATIONS:
1) Search only works when user types in title of product, description, price, or ID will not work. The search is not case-sensitive
however.
2) No monetary system, buying a product deletes it.
'''

from PyQt5 import QtCore, QtGui, QtWidgets, Qt
from PyQt5.QtWidgets import QFileDialog, QWidget, QFrame
from helpers.student import get_first_name
from main_funcs import create_account, login, create_new_product, view_recently_added_products, search, buy_product
import os

BASE_PATH = os.path.dirname(__file__)
DATA_FILES_PATH = os.path.join(BASE_PATH, "Data Files")
IMAGES_PATH = os.path.join(BASE_PATH, "Images")
ALL_UNIVERSITIES_FILE = os.path.join(DATA_FILES_PATH, "all_universities.json")
ALL_STUDENT_INFO_FILE = os.path.join(DATA_FILES_PATH, "all_student_info.json")
ALL_PRODUCTS_FILE = os.path.join(DATA_FILES_PATH, "all_products.json")
BACKGROUND_IMG_PATH = os.path.join(IMAGES_PATH, "background_img.jpg")
LOGO_IMG_PATH = os.path.join(IMAGES_PATH, "logo_earth.jpg")
# StackedWidget indices:
# 0 - Create Account Page
# 1 - Log in Page
# 2 - Homepage
# 3 -Search Results Page
# 4 - Add Product Page
# 5 - Buy Product Page


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 550)
        MainWindow.setFixedSize(800, 550)
        MainWindow.setWindowTitle("Student Trading System")
        #QSS Stylesheet file
        sshFile = os.path.join(os.path.dirname(__file__), "style.qss")
        with open(sshFile, "r") as file:
            MainWindow.setStyleSheet(file.read())
        # instance variable for student university name
        self.current_university = ""
        # instance variable for student email:
        self.current_email = ""
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 550))
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidget.setStyleSheet("font-size: 15pt;")

        # -----Create Account Page----- (index 0)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setEnabled(True)
        # self.frame.setFont(QtGui.QFont("sans serif"))
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 550))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_header_4 = QtWidgets.QLabel(self.frame)
        self.label_header_4.setGeometry(QtCore.QRect(0, -10, 800, 115))
        self.label_header_4.setStyleSheet("background-color:rgb(155,155,155); border-radius: 20px; font-size: 30px;")
        self.label_header_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_header_4.setWordWrap(False)
        self.label_header_4.setObjectName("label_header_4")
        self.line_edit_new_university = QtWidgets.QLineEdit(self.frame)
        self.line_edit_new_university.setGeometry(
            QtCore.QRect(550, 200, 161, 31))
        self.line_edit_new_university.setMaxLength(100)
        self.line_edit_new_university.setClearButtonEnabled(False)
        self.line_edit_new_university.setObjectName("line_edit_new_university")
        self.line_edit_new_name = QtWidgets.QLineEdit(self.frame)
        self.line_edit_new_name.setGeometry(QtCore.QRect(550, 250, 161, 31))
        self.line_edit_new_name.setObjectName("line_edit_new_name")
        self.line_edit_new_email = QtWidgets.QLineEdit(self.frame)
        self.line_edit_new_email.setGeometry(QtCore.QRect(550, 300, 161, 31))
        self.line_edit_new_email.setObjectName("line_edit_new_email")
        self.line_edit_new_password = QtWidgets.QLineEdit(self.frame)
        self.line_edit_new_password.setGeometry(
            QtCore.QRect(550, 350, 161, 31))
        self.line_edit_new_password.setObjectName("line_edit_new_password")
        self.line_edit_new_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.button_create_account = QtWidgets.QPushButton(self.frame)
        self.button_create_account.setGeometry(QtCore.QRect(565, 410, 131, 32))
        self.button_create_account.setObjectName("button_create_account")
        self.button_create_account.clicked.connect(self.init_create_account)
        self.left_line_4 = QtWidgets.QFrame(self.frame)
        self.left_line_4.setGeometry(QtCore.QRect(550, 460, 50, 16))
        self.left_line_4.setStyleSheet("")
        self.left_line_4.setLineWidth(3)
        self.left_line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.left_line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.left_line_4.setObjectName("left_line_4")
        self.right_line_4 = QtWidgets.QFrame(self.frame)
        self.right_line_4.setGeometry(QtCore.QRect(661, 460, 50, 16))
        self.right_line_4.setLineWidth(3)
        self.right_line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.right_line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.right_line_4.setObjectName("right_line_4")
        self.label_or_4 = QtWidgets.QLabel(self.frame)
        self.label_or_4.setGeometry(QtCore.QRect(620, 456, 25, 20))
        self.label_or_4.setStyleSheet("font-size:25px;")
        self.label_or_4.setLineWidth(1)
        self.label_or_4.setObjectName("label_or_4")
        self.button_go_login_page = QtWidgets.QPushButton(self.frame)
        self.button_go_login_page.setGeometry(QtCore.QRect(575, 492, 111, 32))
        self.button_go_login_page.setObjectName("button_go_login_page")
        self.button_go_login_page.clicked.connect(self.show_login_page)
        self.background_img_label_4 = QtWidgets.QLabel(self.frame)
        self.background_img_label_4.setEnabled(True)
        self.background_img_label_4.setGeometry(
            QtCore.QRect(-670, -540, 1511, 1181))
        self.background_img_label_4.setCursor(
            QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.background_img_label_4.setStyleSheet("")
        self.background_img_label_4.setText("")
        self.background_img_label_4.setPixmap(
            QtGui.QPixmap(BACKGROUND_IMG_PATH))
        self.background_img_label_4.setObjectName("background_img_label_4")
        self.logo_img_label_4 = QtWidgets.QLabel(self.frame)
        self.logo_img_label_4.setGeometry(QtCore.QRect(40, 200, 200, 200))
        self.logo_img_label_4.setText("")
        self.logo_img_label_4.setPixmap(QtGui.QPixmap(LOGO_IMG_PATH))
        self.logo_img_label_4.setScaledContents(True)
        self.logo_img_label_4.setObjectName("logo_img_label_4")
        self.background_img_label_4.raise_()
        self.line_edit_new_name.raise_()
        self.button_go_login_page.raise_()
        self.right_line_4.raise_()
        self.label_or_4.raise_()
        self.label_header_4.raise_()
        self.line_edit_new_university.raise_()
        self.button_create_account.raise_()
        self.line_edit_new_email.raise_()
        self.left_line_4.raise_()
        self.line_edit_new_password.raise_()
        self.logo_img_label_4.raise_()
        # -----Log in Page----- (Index 1)
        self.stackedWidget.addWidget(self.page)
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.frame_2 = QtWidgets.QFrame(self.page_login)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 800, 570))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_header_8 = QtWidgets.QLabel(self.frame_2)
        self.label_header_8.setGeometry(QtCore.QRect(0, -10, 800, 115))
        self.label_header_8.setStyleSheet("background-color:rgb(155,155,155); border-radius: 20px; font-size: 30px;")
        self.label_header_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_header_8.setWordWrap(False)
        self.label_header_8.setObjectName("label_header_8")
        self.line_edit_enter_university = QtWidgets.QLineEdit(self.frame_2)
        self.line_edit_enter_university.setGeometry(
            QtCore.QRect(550, 225, 161, 31))
        self.line_edit_enter_university.setObjectName(
            "line_edit_enter_university")
        self.line_edit_enter_email = QtWidgets.QLineEdit(self.frame_2)
        self.line_edit_enter_email.setGeometry(QtCore.QRect(550, 275, 161, 31))
        self.line_edit_enter_email.setObjectName("line_edit_enter_email")
        self.line_edit_enter_password = QtWidgets.QLineEdit(self.frame_2)
        self.line_edit_enter_password.setGeometry(
            QtCore.QRect(550, 325, 161, 31))
        self.line_edit_enter_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_enter_password.setObjectName("line_edit_enter_password")
        self.log_in_button_4 = QtWidgets.QPushButton(self.frame_2)
        self.log_in_button_4.setGeometry(QtCore.QRect(575, 385, 111, 32))
        self.log_in_button_4.setObjectName("log_in_button_4")
        self.log_in_button_4.clicked.connect(self.init_login)
        self.button_back = QtWidgets.QPushButton(self.frame_2)
        self.button_back.setGeometry(QtCore.QRect(575, 430, 111, 32))
        self.button_back.clicked.connect(self.show_create_account_page)
        self.background_img_label_8 = QtWidgets.QLabel(self.frame_2)
        self.background_img_label_8.setEnabled(True)
        self.background_img_label_8.setGeometry(
            QtCore.QRect(-670, -540, 1511, 1181))
        self.background_img_label_8.setStyleSheet("")
        self.background_img_label_8.setText("")
        self.background_img_label_8.setPixmap(
            QtGui.QPixmap(BACKGROUND_IMG_PATH))
        self.background_img_label_8.setObjectName("background_img_label_8")
        self.logo_img_label_8 = QtWidgets.QLabel(self.frame_2)
        self.logo_img_label_8.setGeometry(QtCore.QRect(40, 200, 200, 200))
        self.logo_img_label_8.setText("")
        self.logo_img_label_8.setPixmap(QtGui.QPixmap(LOGO_IMG_PATH))
        self.logo_img_label_8.setScaledContents(True)
        self.logo_img_label_8.setObjectName("logo_img_label_8")
        self.background_img_label_8.raise_()
        self.log_in_button_4.raise_()
        self.line_edit_enter_university.raise_()
        self.line_edit_enter_email.raise_()
        self.line_edit_enter_password.raise_()
        self.logo_img_label_8.raise_()
        self.button_back.raise_()
        self.label_header_8.raise_()
        # -----Homepage----- (index 2)
        self.stackedWidget.addWidget(self.page_login)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_homepage = QtWidgets.QFrame(self.page_3)
        self.frame_homepage.setGeometry(QtCore.QRect(0, 0, 800, 550))
        self.frame_homepage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_homepage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_edit_search_homepage = QtWidgets.QLineEdit(self.frame_homepage)
        self.line_edit_search_homepage.setGeometry(
            QtCore.QRect(220, 120, 350, 31))
        self.line_edit_search_homepage.setObjectName(
            "line_edit_new_password_11")
        self.line_edit_search_homepage.returnPressed.connect(self.go_search)
        self.button_add_product = QtWidgets.QPushButton(self.frame_homepage)
        self.button_add_product.setGeometry(
            QtCore.QRect(670, 110, 110, 45))
        self.button_add_product.setObjectName("button_go_login_page_15")
        self.button_add_product.clicked.connect(self.show_add_product_page)

        self.button_logout1 = QtWidgets.QPushButton(self.frame_homepage)
        self.button_logout1.setGeometry(QtCore.QRect(700, 30, 80, 40))
        self.button_logout1.setObjectName("button_logout_7")
        self.button_logout1.clicked.connect(self.logout)
        self.logo_img_label_15 = QtWidgets.QLabel(self.page_3)
        self.logo_img_label_15.setGeometry(QtCore.QRect(10, 110, 50, 50))
        self.logo_img_label_15.setText("Testing...")
        self.logo_img_label_15.setPixmap(QtGui.QPixmap(LOGO_IMG_PATH))
        self.logo_img_label_15.setScaledContents(True)
        self.button_add_product.raise_()
        self.button_logout1.raise_()
        self.line_edit_search_homepage.raise_()
        self.stackedWidget.addWidget(self.page_3)
        #-----Search Results----- (Index 3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.frame_11 = QtWidgets.QFrame(self.page_4)
        self.frame_11.setGeometry(QtCore.QRect(0, 0, 800, 550))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.line_edit_search_results_page = QtWidgets.QLineEdit(self.frame_11)
        self.line_edit_search_results_page.setGeometry(
            QtCore.QRect(220, 120, 350, 31))
        self.line_edit_search_results_page.returnPressed.connect(self.go_search)

        self.button_add_product_search_results = QtWidgets.QPushButton(self.frame_11)
        self.button_add_product_search_results.setGeometry(QtCore.QRect(670, 110, 110, 45))
        self.button_add_product_search_results.clicked.connect(self.show_add_product_page)
        self.button_search_results_home = QtWidgets.QPushButton(self.frame_11)
        self.button_search_results_home.setGeometry(QtCore.QRect(670, 170, 110, 45))
        self.button_search_results_home.clicked.connect(self.show_homepage)
        self.button_logout_8 = QtWidgets.QPushButton(self.frame_11)
        self.button_logout_8.setGeometry(QtCore.QRect(700, 30, 80, 40))
        self.button_logout_8.clicked.connect(self.show_create_account_page)
        self.logo_img_label_16 = QtWidgets.QLabel(self.frame_11)
        self.logo_img_label_16.setGeometry(QtCore.QRect(10, 110, 50, 50))
        self.logo_img_label_16.setText("")
        self.logo_img_label_16.setPixmap(QtGui.QPixmap(LOGO_IMG_PATH))
        self.logo_img_label_16.setScaledContents(True) 
        self.scrollArea = QtWidgets.QScrollArea(self.frame_11)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setStyleSheet("background: transparent;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setGeometry(QtCore.QRect(130, 180, 550, 350))
        self.scrollAreaLayout = QtWidgets.QVBoxLayout(self.scrollArea)
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 550, 350))
        
        self.scrollAreaWidgetContents.setLayout(self.scrollAreaLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.logo_img_label_16.raise_()
        self.scrollArea.raise_()
        self.button_add_product_search_results.raise_()
        self.button_logout_8.raise_()
        self.line_edit_search_results_page.raise_()
        self.button_search_results_home.raise_()
        self.stackedWidget.addWidget(self.page_4)
        # -----Add Product----- index 4
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.frame_12 = QtWidgets.QFrame(self.page_5)
        self.frame_12.setGeometry(QtCore.QRect(0, 0, 800, 550))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_header_add_product = QtWidgets.QLabel(self.frame_12)
        self.label_header_add_product.setGeometry(QtCore.QRect(250, 20, 400, 60))
        self.label_header_add_product.setStyleSheet("font-size: 40px;")
        self.post_product_button_2 = QtWidgets.QPushButton(self.frame_12)
        self.post_product_button_2.setGeometry(QtCore.QRect(670, 500, 110, 45))
        self.post_product_button_2.setObjectName("post_product_button_2")
        self.post_product_button_2.clicked.connect(self.init_add_product)
        self.button_logout_10 = QtWidgets.QPushButton(self.frame_12)
        self.button_logout_10.setGeometry(QtCore.QRect(700, 30, 80, 40))
        self.button_logout_10.setObjectName("button_logout_10")
        self.button_logout_10.clicked.connect(self.logout)
        self.logo_img_label_18 = QtWidgets.QLabel(self.frame_12)
        self.logo_img_label_18.setGeometry(QtCore.QRect(10, 110, 50, 50))
        self.logo_img_label_18.setText("")
        self.logo_img_label_18.setPixmap(QtGui.QPixmap(LOGO_IMG_PATH))
        self.logo_img_label_18.setScaledContents(True)
        self.logo_img_label_18.setObjectName("logo_img_label_18")
        # initialization of self.image
        self.img_label_path = ""
        self.go_home_button_2 = QtWidgets.QPushButton(self.frame_12)
        self.go_home_button_2.setGeometry(QtCore.QRect(670, 110, 110, 45))
        self.go_home_button_2.setObjectName("go_home_button_2")
        self.go_home_button_2.clicked.connect(self.show_homepage)
        self.label_selected_image = QtWidgets.QLabel(self.frame_12)
        self.label_selected_image.setGeometry(QtCore.QRect(30, 220, 150, 190))
        self.label_selected_image.setStyleSheet("border: 2px solid black;\n"
                                                "")
        self.label_selected_image.setObjectName("label_selected_image")
        self.button_select_img_label = QtWidgets.QPushButton(self.frame_12)
        self.button_select_img_label.setGeometry(
            QtCore.QRect(55, 170, 100, 32))
        self.button_select_img_label.setObjectName("button_select_img_label")
        self.button_select_img_label.clicked.connect(self.open_image)
        self.add_product_name_line_edit = QtWidgets.QLineEdit(self.frame_12)
        self.add_product_name_line_edit.setGeometry(
            QtCore.QRect(280, 220, 171, 41))
        self.add_product_name_line_edit.setText("")
        self.add_product_name_line_edit.setObjectName(
            "add_product_name_line_edit")
        self.add_product_price_line_edit = QtWidgets.QLineEdit(self.frame_12)
        self.add_product_price_line_edit.setGeometry(
            QtCore.QRect(530, 220, 171, 41))
        self.add_product_price_line_edit.setObjectName(
            "add_product_price_line_edit")
        self.add_product_description_line_edit = QtWidgets.QTextEdit(
            self.frame_12)
        self.add_product_description_line_edit.setGeometry(
            QtCore.QRect(280, 280, 221, 91))
        self.add_product_description_line_edit.setObjectName(
            "add_product_description_line_edit")
        self.logo_img_label_18.raise_()
        self.go_home_button_2.raise_()
        self.label_selected_image.raise_()
        self.button_select_img_label.raise_()
        self.add_product_name_line_edit.raise_()
        self.add_product_price_line_edit.raise_()
        self.add_product_description_line_edit.raise_()
        self.button_logout_10.raise_()
        self.post_product_button_2.raise_()
        self.stackedWidget.addWidget(self.page_5)
        #-----Buy Product Page----- (index 5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.frame_13 = QtWidgets.QFrame(self.page_6)
        self.frame_13.setGeometry(QtCore.QRect(0, 0, 800, 570))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_header_buy_product = QtWidgets.QLabel(self.frame_13)
        self.label_header_buy_product.setGeometry(QtCore.QRect(260, 20, 400, 60))
        self.label_header_buy_product.setStyleSheet("font-size: 40px;")
        self.button_buy_product = QtWidgets.QPushButton(self.frame_13)
        self.button_buy_product.setGeometry(QtCore.QRect(670, 500, 110, 45))
        self.button_logout_19 = QtWidgets.QPushButton(self.frame_13)
        self.button_logout_19.setGeometry(QtCore.QRect(700, 30, 80, 40))
        self.button_logout_19.clicked.connect(self.logout)
        self.logo_img_label_27 = QtWidgets.QLabel(self.frame_13)
        self.logo_img_label_27.setGeometry(QtCore.QRect(10, 110, 50, 50))
        self.logo_img_label_27.setText("")
        self.logo_img_label_27.setPixmap(QtGui.QPixmap(LOGO_IMG_PATH))
        self.logo_img_label_27.setScaledContents(True)
        self.logo_img_label_27.setObjectName("logo_img_label_27")
        self.go_home_button_11 = QtWidgets.QPushButton(self.frame_13)
        self.go_home_button_11.setGeometry(QtCore.QRect(670, 110, 110, 45))
        self.go_home_button_11.clicked.connect(self.show_homepage)
        self.label_buy_product_img = QtWidgets.QLabel(self.frame_13)
        self.label_buy_product_img.setGeometry(
            QtCore.QRect(20, 170, 220, 270))
        self.label_buy_product_img.setStyleSheet("border: 2px solid black;\n"
                                                     "")
        self.label_buy_product_img.setObjectName(
            "label_buy_product_img")
        self.label_buy_product_title = QtWidgets.QLabel(self.frame_13)
        self.label_buy_product_title.setGeometry(QtCore.QRect(290, 190, 300, 80))
        self.label_buy_product_title.setObjectName("label_buy_product_title")
        self.label_buy_product_title.setStyleSheet("font-size: 30px;")
        self.label_buy_product_title.setWordWrap(True)
        self.label_buy_product_description = QtWidgets.QLabel(self.frame_13)
        self.label_buy_product_description.setGeometry(QtCore.QRect(290, 310, 290, 250))
        self.label_buy_product_description.setObjectName("label_buy_product_description")
        self.label_buy_product_description.setStyleSheet("font-size: 20px;")
        self.label_buy_product_description.setWordWrap(True)
        self.label_buy_product_price = QtWidgets.QLabel(self.frame_13)
        self.label_buy_product_price.setGeometry(QtCore.QRect(610, 218, 150, 50))
        self.label_buy_product_price.setObjectName("label_buy_product_price")
        self.label_buy_product_price.setStyleSheet("font-size:25px;")
        self.logo_img_label_27.raise_()
        self.go_home_button_11.raise_()
        self.label_buy_product_img.raise_()
        self.label_buy_product_title.raise_()
        self.label_buy_product_description.raise_()
        self.label_buy_product_price.raise_()
        self.button_logout_19.raise_()
        self.button_buy_product.raise_()
        self.label_header_add_product.raise_()
        self.label_header_buy_product.raise_()
        self.stackedWidget.addWidget(self.page_6)
        MainWindow.setCentralWidget(self.centralwidget)

        #Text displayed when there are no products that match the search
        self.no_results_msg = QtWidgets.QLabel(self.frame_11)
        self.no_results_msg.hide()
        self.no_results_msg.setGeometry(75, 190, 650, 200)
        self.no_results_msg.raise_()
        self.no_results_msg.setWordWrap(True)
        self.no_results_msg.setStyleSheet("font-size: 20pt;")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_header_4.setText(_translate(
            "MainWindow", "Student Trading System"))
        self.line_edit_new_university.setPlaceholderText(
            _translate("MainWindow", "  Enter University..."))
        self.line_edit_new_name.setPlaceholderText(
            _translate("MainWindow", "  Enter name...."))
        self.line_edit_new_email.setPlaceholderText(
            _translate("MainWindow", "  Enter email..."))
        self.line_edit_new_password.setPlaceholderText(
            _translate("MainWindow", "  Enter password..."))
        self.button_create_account.setText(
            _translate("MainWindow", "Create Account"))
        self.label_or_4.setText(_translate("MainWindow", "or"))
        self.button_go_login_page.setText(_translate("MainWindow", "Log In"))
        self.label_header_8.setText(_translate(
            "MainWindow", "Student Trading System"))
        self.line_edit_enter_university.setPlaceholderText(
            _translate("MainWindow", "  Enter university...."))
        self.line_edit_enter_email.setPlaceholderText(
            _translate("MainWindow", "  Enter email..."))
        self.line_edit_enter_password.setPlaceholderText(
            _translate("MainWindow", "  Enter password..."))
        self.log_in_button_4.setText(_translate("MainWindow", "Log in"))
        self.button_back.setText(_translate("MainWindow", " <-- Back"))
        self.line_edit_search_homepage.setPlaceholderText(
            _translate("MainWindow", "  Search..."))
        self.button_add_product.setText(
            _translate("MainWindow", "Add Product"))
        self.button_logout1.setText(_translate("MainWindow", "Logout"))
        self.line_edit_search_results_page.setPlaceholderText(
            _translate("MainWindow", "  Search..."))
        self.button_add_product_search_results.setText(
            _translate("MainWindow", "Add Product"))
        self.button_search_results_home.setText(_translate("MainWindow", "Home"))
        self.button_logout_8.setText(_translate("MainWindow", "Logout"))
        self.post_product_button_2.setText(
            _translate("MainWindow", "Post Product"))
        self.button_logout_10.setText(_translate("MainWindow", "Logout"))
        self.go_home_button_2.setText(_translate("MainWindow", "Home"))
        self.label_selected_image.setText(
            _translate("MainWindow", "      Select Image..."))
        self.label_header_add_product.setText(_translate("MainWindow", "Add a Product"))
        self.button_select_img_label.setText(
            _translate("MainWindow", "Select Image"))
        self.add_product_name_line_edit.setPlaceholderText(
            _translate("MainWindow", "  Product Name..."))
        self.add_product_price_line_edit.setPlaceholderText(
            _translate("MainWindow", "  Price $..."))
        self.add_product_description_line_edit.setPlaceholderText(
            _translate("MainWindow", "Product Description..."))
        self.button_buy_product.setText(
            _translate("MainWindow", "Buy Product"))
        self.button_logout_19.setText(_translate("MainWindow", "Logout"))
        self.go_home_button_11.setText(_translate("MainWindow", "Home"))
        self.label_buy_product_img.setText(_translate(
            "MainWindow", "              Image..."))
        self.label_buy_product_title.setText(_translate("MainWindow", "Title"))
        self.label_header_buy_product.setText(_translate("MainWindow", "Buy a Product"))
        self.label_buy_product_description.setText(_translate("MainWindow", "Description"))
        self.label_buy_product_price.setText(_translate("MainWindow", "Price"))

    def init_create_account(self):
        university = self.line_edit_new_university.text()
        new_name = self.line_edit_new_name.text()
        new_email = self.line_edit_new_email.text()
        new_password = self.line_edit_new_password.text()
        if create_account(university, new_name, new_email, new_password):
            self.current_university = university
            self.current_email = new_email
          # Changes the page being displayed to the homepage
            self.show_homepage()
            self.line_edit_new_university.setText("")
            self.line_edit_new_name.setText("")
            self.line_edit_new_password.setText("")
            self.line_edit_new_password.setText("")

    def show_login_page(self):
        self.stackedWidget.setCurrentIndex(1)

    def show_homepage(self):
        self.line_edit_search_homepage.setText("")
        self.line_edit_search_homepage.setFocus()

        # Delete previously displayed Product_Template instances
        for child in self.frame_homepage.findChildren(QFrame):
            child.deleteLater()

        #Welcome label for homepage
        label_welcome = QtWidgets.QLabel(self.frame_homepage)
        label_welcome.setGeometry(QtCore.QRect(20, 20, 400, 50))
        label_welcome.show()
        label_welcome.raise_()
        label_welcome.setStyleSheet("font-size: 30px;")

        student_name = get_first_name(ALL_STUDENT_INFO_FILE, self.current_email)
        label_welcome.setText(f"Welcome,  {student_name}!")
        self.stackedWidget.setCurrentIndex(2)
        self.logo_img_label_15.raise_()
        
        recently_added_products = view_recently_added_products(self.current_university)
        #If view_recently_added_products does not return a list
        if type(recently_added_products) == str:
            #Text displayed when there are no products to display on the home page
            homepage_msg = QtWidgets.QLabel(self.frame_homepage)
            homepage_msg.setGeometry(175, 163, 500, 200)
            homepage_msg.setStyleSheet("font-size: 30pt;")
            homepage_msg.setText(recently_added_products)
            homepage_msg.raise_()
            homepage_msg.show()
        else:
            x = 20
            y = 175
            pos = 0
            for _ in range(len(recently_added_products)):
                if pos+1 > len(recently_added_products):
                    break
                else:
                    Product_Template(x, y, recently_added_products[pos], recently_added_products[pos+1][0], recently_added_products[pos+1][1], recently_added_products[pos+1][2], recently_added_products[pos+1][3], self.frame_homepage, self.view_product).display()
                x += 195
                if x > 615:
                    x = 20
                    y = 360
                pos += 2

    def go_search(self):
        self.show_search_results_page()
        self.no_results_msg.hide()
        for child in self.scrollArea.findChildren(QFrame):
            child.deleteLater()
        search_results = search(self.current_university, (self.line_edit_search_homepage.text() if len(self.line_edit_search_homepage.text()) > 0 else self.line_edit_search_results_page.text()))
        self.line_edit_search_homepage.setText("")
        self.line_edit_search_results_page.setText("")
        if type(search_results) == str:
            self.no_results_msg.setText(search_results)
            self.no_results_msg.show()
        else:
            x = 50
            y = 50
            pos = 0
            for _ in range(len(search_results)):
                if pos+1 > len(search_results):
                    break
                else:
                    Search_Template(x, y, search_results[pos], search_results[pos+1][0], search_results[pos+1][1], search_results[pos+1][2], search_results[pos+1][3], self.scrollAreaLayout, self.view_product).display()
                y += 80
                pos += 2

    def show_buy_page(self):
        self.stackedWidget.setCurrentIndex(5)

    def show_create_account_page(self):
        self.line_edit_new_university.setText("")
        self.line_edit_new_name.setText("")
        self.line_edit_new_email.setText("")
        self.line_edit_new_password.setText("")
        self.stackedWidget.setCurrentIndex(0)

    def show_add_product_page(self):
        self.stackedWidget.setCurrentIndex(4)
        self.add_product_name_line_edit.setFocus()

    def show_search_results_page(self):
        self.stackedWidget.setCurrentIndex(3)

    def init_login(self):
        university = self.line_edit_enter_university.text()
        email = self.line_edit_enter_email.text()
        password = self.line_edit_enter_password.text()
        if login(university, email, password):
            self.current_university = university
            self.current_email = email
            self.show_homepage()
        self.line_edit_enter_password.setText("")
        self.line_edit_enter_email.setText("")
        self.line_edit_enter_university.setText("")

    def logout(self):
        self.show_create_account_page()

    def init_add_product(self):
        new_name = self.add_product_name_line_edit.text()
        # toPlainText() used for QTextEdits only
        new_description = self.add_product_description_line_edit.toPlainText()
        new_price = self.add_product_price_line_edit.text()
        if len(new_name) and len(new_description) and len(new_price) != 0:
            create_new_product(self.current_university, self.current_email,
                               new_name, new_description, new_price, self.img_label_path)
            self.add_product_name_line_edit.setText("")
            self.add_product_price_line_edit.setText("")
            self.add_product_description_line_edit.setText("")
            pixmap = QtGui.QPixmap(None)
            self.label_selected_image.setPixmap(pixmap)
            self.show_homepage()

    def open_image(self):
        # self.image_path initialized in setupUI method
        self.img_label_path = QFileDialog.getOpenFileName(
            MainWindow, "Choose Image", IMAGES_PATH, "Image Files (*.jpg *.png)")[0]
        pixmap = QtGui.QPixmap(self.img_label_path)
        self.label_selected_image.setPixmap(pixmap.scaled(self.label_selected_image.width(), self.label_selected_image.height(), QtCore.Qt.KeepAspectRatio, QtCore.Qt.FastTransformation))

    def buy_product(self, product_id):
        buy_product(self.current_university, self.current_email, product_id)
        self.show_homepage()

    def view_product(self, product_id, title, description, price, img_path):
        self.show_buy_page()
        self.label_buy_product_title.setText(title)
        self.label_buy_product_title.setWordWrap(True)
        self.label_buy_product_description.setText(description)
        self.label_buy_product_description.setWordWrap(True)
        self.label_buy_product_price.setText(f"${price}")
        self.label_buy_product_price.setWordWrap(True)
        pixmap = QtGui.QPixmap(img_path)
        self.label_buy_product_img.setPixmap(pixmap.scaled(self.label_buy_product_img.width(), self.label_buy_product_img.height(), QtCore.Qt.KeepAspectRatio, QtCore.Qt.FastTransformation))
        self.button_buy_product.clicked.connect(lambda: self.buy_product(product_id))
        
class Product_Template(QFrame):
    clicked = QtCore.pyqtSignal()
    def __init__(self, xcoord, ycoord, product_id, title, description, price, img_path, parent_frame, method):
        super().__init__(parent_frame)
        self.xcoord = xcoord
        self.ycoord = ycoord
        self.product_id = product_id
        self.title = title
        self.description = description
        self.price = price
        self.img_path = img_path
        self.parent_frame = parent_frame
        self.method = method
        self.setGeometry(QtCore.QRect(self.xcoord, self.ycoord, 190, 180))
        self.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clicked.connect(lambda: self.method(self.product_id, self.title, self.description, self.price, self.img_path))
        self.img_label = QtWidgets.QLabel(self)
        self.img_label.setGeometry(QtCore.QRect(2, 2, 101, 81))
        self.img_label.setStyleSheet("border: 2px solid black;")
        self.img_label.setObjectName("img_label")
        pixmap = QtGui.QPixmap(self.img_path)
        self.img_label.setPixmap(pixmap.scaled(self.img_label.width(), self.img_label.height(), QtCore.Qt.KeepAspectRatio, QtCore.Qt.FastTransformation))
        self.price_label = QtWidgets.QLabel(self)
        self.price_label.setGeometry(QtCore.QRect(102, 50, self.width() - self.img_label.width(), 40))
        self.price_label.setObjectName("price_label")
        self.price_label.setText(f"${self.price}")
        self.title_label = QtWidgets.QLabel(self)
        self.title_label.setGeometry(QtCore.QRect(102, 0, self.width()-self.img_label.width(), 50))
        self.title_label.setObjectName("title_label")
        self.title_label.setText(self.title)
        self.title_label.setStyleSheet("text-decoration: underline; color:black; justify-content: center; font-size: 15px;")
        self.description_label = QtWidgets.QLabel(self)
        self.description_label.setGeometry(QtCore.QRect(5, 80, self.width()-2, 75))
        self.description_label.setObjectName("description_label")
        self.description_label.setText(self.description)
        self.description_label.setWordWrap(True)

    def display(self):
        self.show()
        self.raise_()

    def mousePressEvent(self, event):
        self.clicked.emit()

    def get_product_id(self):
        return self.product_id

class Search_Template(QFrame):
    clicked = QtCore.pyqtSignal()
    def __init__(self, xcoord, ycoord, product_id, title, description, price, img_path, parent_widget, method):
        super().__init__(parent=None)
        self.product_id = product_id
        self.title = title
        self.description = description
        self.price = price
        self.img_path = img_path
        self.parent_widget = parent_widget
        self.method = method
        self.setGeometry(QtCore.QRect(xcoord, ycoord, 549, 140)) #Original x, y, coords were 0, 0
        self.setStyleSheet("")
        self.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setFrameShadow(QtWidgets.QFrame.Raised)
        self.parent_widget.addWidget(self)
        self.clicked.connect(lambda: self.method(product_id, title, description, price, img_path))
        self.template_frame_img_label = QtWidgets.QLabel(self)
        self.template_frame_img_label.setGeometry(QtCore.QRect(0, 0, 121, 141))
        pixmap = QtGui.QPixmap(self.img_path)
        self.template_frame_img_label.setPixmap(pixmap.scaled(self.template_frame_img_label.width(), self.template_frame_img_label.height(), QtCore.Qt.KeepAspectRatio, QtCore.Qt.FastTransformation))
        self.template_frame_title_label = QtWidgets.QLabel(self)
        self.template_frame_title_label.setGeometry(QtCore.QRect(130, 0, 291, 40))
        self.template_frame_title_label.setText(self.title)
        self.template_frame_title_label.setWordWrap(True)
        self.template_frame_description_label = QtWidgets.QLabel(self)
        self.template_frame_description_label.setGeometry(QtCore.QRect(130, 40, 291, 91))
        self.template_frame_description_label.setText(self.description)
        self.template_frame_description_label.setWordWrap(True)
        self.template_frame_price_label = QtWidgets.QLabel(self)
        self.template_frame_price_label.setGeometry(QtCore.QRect(120, 120, 101, 16))
        self.template_frame_price_label.setText(f" ${self.price}")

    def display(self):
        self.show()
        self.raise_()

    def mousePressEvent(self, event):
        self.clicked.emit()

    def get_product_id(self):
        return self.product_id
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
